default_stages: [commit, push]

default_language_version:
  python: python3.8

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: no-commit-to-branch
      - id: debug-statements
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E731,W503,W504
  - repo: git://github.com/Lucas-C/pre-commit-hooks.git
    sha: v1.1.9
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        args: ["--whitespaces-count", "2"] # defaults to: 4
  - repo: git://github.com/trbs/pre-commit-hooks-trbs.git
    sha: e233916fb2b4b9019b4a3cc0497994c7926fe36b
    hooks:
      - id: forbid-executables
        exclude: manage.py|setup.py
  #-   repo: git://github.com/pre-commit/mirrors-csslint
  #    sha: v1.0.5
  #    hooks:
  #    -   id: csslint
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
